#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Apr 24 06:59:28 GMT-03:00 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
