
["Damage Settings"]
	#Sword skill damage multiplier
	#Range: 0.1 ~ 1000.0
	damageMultiplier = 1.0
	#Sword skill cool down multiplier
	#Range: 0.01 ~ 10.0
	CoolDownMultiplier = 1.0
	#The available weapons are set automatically to some extent.
	AutoWeaponSetting = false
	#Allow PVP with sword skills
	pvp = false
	#Enable Sword Skill Unlock
	UnlockedSkill = true
	#Include neutral mobs as attack targets
	attackNeutralMobs = true

["SP Settings"]
	#Default maximum SP value
	#Range: 1.0 ~ 10000.0
	defaultMaxSP = 100.0
	#Default SP regeneration value per second
	#Range: 0.0 ~ 1000.0
	defaultSPRegen = 1.0

