
["SwordSkillEffect Settings"]
	#Please adjust according to the Shader
	#Range: 0 ~ 3
	SwordSkillEffect_System = 0

	["SwordSkillEffect Settings"."HUD Settings"]
		#Range: -1920 ~ 1920
		hudPosX = 0
		#Range: -1080 ~ 1080
		hudPosY = 0
		#Range: 1 ~ 64
		hudScale = 24

